<script type="text/javascript" src="./assets/plugins/jquery/jquery.min.js"></script>
<script type="text/javascript" src="./assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
<script type="text/javascript" src="./assets/plugins/bootstrap-daterangepicker/js/daterangepicker.js"></script>
<script type="text/javascript" src="./assets/plugins/jquery-ui/js/jquery-ui.js"></script>
<script type="text/javascript" src="./assets/js/admin/vendor.min.js"></script>
<script type="text/javascript" src="./assets/js/admin/app.min.js"></script>
<script type="text/javascript" src="./assets/js/admin/prototype.min.js"></script>
<script type="text/javascript" src="./assets/js/admin/common.min.js"></script>
<script type="text/javascript" src="./assets/js/admin/rest.min.js"></script>
<script type="text/javascript" src="./assets/js/admin/clock.min.js"></script>
<script type="text/javascript" src="./assets/plugins/summernote/summernote-lite.min.js"></script>
<script type="text/javascript" src="./assets/plugins/jstree/jstree.min.js"></script>